const worksList = [{
 id: 1,
 name: "Textile Factory" ,
 subtitule: "Website for textile factory",
 img:"work7.jpeg",
 p1: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
 p2: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
 p3: "",
 proyectLink:"",
 codeLink:"",
},
{
  id: 2,
  name: "E-Commerce",
  subtitule: "Final Proyect of JS",
  img:"",
  p1: "",
  p2: "",
  p3: "",
  proyectLink:"",
  codeLink:"",
},
{
  id: 3,
  name: "Wines Web",
  subtitule: "Final proyect of web design",
  img:"",
  p1: "",
  p2: "",
  p3: "",
  proyectLink:"",
  codeLink:"",
},
{
  id: 4,
  name: "Social Web",
  subtitule: "Own proyect",
  img:"",
  p1: "",
  p2: "",
  p3: "",
  proyectLink:"",
  codeLink:"",
}]
